// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz8J2YdIjmYDXsZ7uNakPsqSGBcMXpmao',
    appId: '1:793925516839:web:77b4202edbe87c6b749802',
    messagingSenderId: '793925516839',
    projectId: 'ecommerce-app-d2b37',
    authDomain: 'ecommerce-app-d2b37.firebaseapp.com',
    storageBucket: 'ecommerce-app-d2b37.firebasestorage.app',
    measurementId: 'G-TCN4MKJ1X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7hqO5hBrmxyR1Fjq0TvbPffG6s2VevNw',
    appId: '1:793925516839:android:35de2254318ff1b3749802',
    messagingSenderId: '793925516839',
    projectId: 'ecommerce-app-d2b37',
    storageBucket: 'ecommerce-app-d2b37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK7SqKcOrQb7E_4MLbSimz3vx2Qvse4Lw',
    appId: '1:793925516839:ios:82d26f342fe3110b749802',
    messagingSenderId: '793925516839',
    projectId: 'ecommerce-app-d2b37',
    storageBucket: 'ecommerce-app-d2b37.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK7SqKcOrQb7E_4MLbSimz3vx2Qvse4Lw',
    appId: '1:793925516839:ios:82d26f342fe3110b749802',
    messagingSenderId: '793925516839',
    projectId: 'ecommerce-app-d2b37',
    storageBucket: 'ecommerce-app-d2b37.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz8J2YdIjmYDXsZ7uNakPsqSGBcMXpmao',
    appId: '1:793925516839:web:21cf386807be4b96749802',
    messagingSenderId: '793925516839',
    projectId: 'ecommerce-app-d2b37',
    authDomain: 'ecommerce-app-d2b37.firebaseapp.com',
    storageBucket: 'ecommerce-app-d2b37.firebasestorage.app',
    measurementId: 'G-PMZ385GLVJ',
  );
}
